// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: protos/loans.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BorrowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowRequest) Reset() {
	*x = BorrowRequest{}
	mi := &file_protos_loans_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowRequest) ProtoMessage() {}

func (x *BorrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_loans_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowRequest.ProtoReflect.Descriptor instead.
func (*BorrowRequest) Descriptor() ([]byte, []int) {
	return file_protos_loans_proto_rawDescGZIP(), []int{0}
}

func (x *BorrowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BorrowRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type ReturnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnRequest) Reset() {
	*x = ReturnRequest{}
	mi := &file_protos_loans_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnRequest) ProtoMessage() {}

func (x *ReturnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_loans_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnRequest.ProtoReflect.Descriptor instead.
func (*ReturnRequest) Descriptor() ([]byte, []int) {
	return file_protos_loans_proto_rawDescGZIP(), []int{1}
}

func (x *ReturnRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

type LoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *UserResponse          `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Book          *BookResponse          `protobuf:"bytes,3,opt,name=book,proto3" json:"book,omitempty"`
	BorrowedDate  string                 `protobuf:"bytes,4,opt,name=borrowed_date,json=borrowedDate,proto3" json:"borrowed_date,omitempty"` // Формат: RFC3339 "2006-01-02T15:04:05Z07:00"
	DueDate       string                 `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	ReturnedDate  string                 `protobuf:"bytes,6,opt,name=returned_date,json=returnedDate,proto3" json:"returned_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanResponse) Reset() {
	*x = LoanResponse{}
	mi := &file_protos_loans_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanResponse) ProtoMessage() {}

func (x *LoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_loans_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanResponse.ProtoReflect.Descriptor instead.
func (*LoanResponse) Descriptor() ([]byte, []int) {
	return file_protos_loans_proto_rawDescGZIP(), []int{2}
}

func (x *LoanResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoanResponse) GetUser() *UserResponse {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoanResponse) GetBook() *BookResponse {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *LoanResponse) GetBorrowedDate() string {
	if x != nil {
		return x.BorrowedDate
	}
	return ""
}

func (x *LoanResponse) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *LoanResponse) GetReturnedDate() string {
	if x != nil {
		return x.ReturnedDate
	}
	return ""
}

var File_protos_loans_proto protoreflect.FileDescriptor

const file_protos_loans_proto_rawDesc = "" +
	"\n" +
	"\x12protos/loans.proto\x12\alibrary\x1a\x12protos/users.proto\x1a\x12protos/books.proto\"A\n" +
	"\rBorrowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\"(\n" +
	"\rReturnRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\"\xd9\x01\n" +
	"\fLoanResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04user\x18\x02 \x01(\v2\x15.library.UserResponseR\x04user\x12)\n" +
	"\x04book\x18\x03 \x01(\v2\x15.library.BookResponseR\x04book\x12#\n" +
	"\rborrowed_date\x18\x04 \x01(\tR\fborrowedDate\x12\x19\n" +
	"\bdue_date\x18\x05 \x01(\tR\adueDate\x12#\n" +
	"\rreturned_date\x18\x06 \x01(\tR\freturnedDate2\x8b\x01\n" +
	"\vLoanService\x12=\n" +
	"\n" +
	"BorrowBook\x12\x16.library.BorrowRequest\x1a\x15.library.LoanResponse\"\x00\x12=\n" +
	"\n" +
	"ReturnBook\x12\x16.library.ReturnRequest\x1a\x15.library.LoanResponse\"\x00B\x06Z\x04.;pbb\x06proto3"

var (
	file_protos_loans_proto_rawDescOnce sync.Once
	file_protos_loans_proto_rawDescData []byte
)

func file_protos_loans_proto_rawDescGZIP() []byte {
	file_protos_loans_proto_rawDescOnce.Do(func() {
		file_protos_loans_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_loans_proto_rawDesc), len(file_protos_loans_proto_rawDesc)))
	})
	return file_protos_loans_proto_rawDescData
}

var file_protos_loans_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_loans_proto_goTypes = []any{
	(*BorrowRequest)(nil), // 0: library.BorrowRequest
	(*ReturnRequest)(nil), // 1: library.ReturnRequest
	(*LoanResponse)(nil),  // 2: library.LoanResponse
	(*UserResponse)(nil),  // 3: library.UserResponse
	(*BookResponse)(nil),  // 4: library.BookResponse
}
var file_protos_loans_proto_depIdxs = []int32{
	3, // 0: library.LoanResponse.user:type_name -> library.UserResponse
	4, // 1: library.LoanResponse.book:type_name -> library.BookResponse
	0, // 2: library.LoanService.BorrowBook:input_type -> library.BorrowRequest
	1, // 3: library.LoanService.ReturnBook:input_type -> library.ReturnRequest
	2, // 4: library.LoanService.BorrowBook:output_type -> library.LoanResponse
	2, // 5: library.LoanService.ReturnBook:output_type -> library.LoanResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_loans_proto_init() }
func file_protos_loans_proto_init() {
	if File_protos_loans_proto != nil {
		return
	}
	file_protos_users_proto_init()
	file_protos_books_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_loans_proto_rawDesc), len(file_protos_loans_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_loans_proto_goTypes,
		DependencyIndexes: file_protos_loans_proto_depIdxs,
		MessageInfos:      file_protos_loans_proto_msgTypes,
	}.Build()
	File_protos_loans_proto = out.File
	file_protos_loans_proto_goTypes = nil
	file_protos_loans_proto_depIdxs = nil
}
